### ISSUE TITLE
why different path have same nodes

### ISSUE THREAD

**Issue by superclocks** [talbaumel/talbaumel.github.io#1]
hi, In https://talbaumel.github.io/softmax/, i found [0, 0, 0, 0] and [0, 0, 0, 1] have same node seq 0 15 30 45, could you show some explanation. and i found code(path, nodes = self.value_to_path_and_nodes_dict[value]) in function get_loss has the same problem, that's mean different path will get the same prob. besides, i don'n konw why these are 14 nodes in your demo tree

**Comment by talbaumel** [comment]
Hi, thanks for the issue!
There was an error in the memoization, I'll upload a fix
