### ISSUE TITLE
what shoud i do, if i want to add it into mxnet

### ISSUE THREAD

**Issue by superclocks** [talbaumel/talbaumel.github.io#2]
hi, i want to use your hs in mxnet, is that ok?

**Comment by talbaumel** [comment]
Sure

**Comment by superclocks** [comment]
hi, i follow the instruction http://mxnet.io/how_to/new_op.html?highlight=customoppropi, but i failed.  could you give me some advice, how to add hs in mxnet

**Comment by talbaumel** [comment]
No idea, never used mxnet
