### ISSUE TITLE
solr err: HTTP 301

### ISSUE THREAD

**Issue by dapeng-ai2** [talbaumel/talbaumel.github.io#3]
Hi Tal,
When I try to run the demo of QCFS & TD-QFS, the server cannot be connected to retrieve the database.
Do you have a version to load the database from local disk. Or you could give me a clue to modify the code to load database locally.
Best Regards,
D Zhang

**Comment by talbaumel** [comment]
Hi Dapeng, in [demo site](https://talbaumel.github.io/QCFS/dataset.html) try clicking the  `Asthma, Lung Cancer, Alzheimer's Disease and Obesity` links in `Document Sets` box.
The solr will probably won't be back because it's out of my control.

Hope it helps

**Comment by talbaumel** [comment]
No response for a while
